//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDCharacterSheetTool.Classes.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DnDDatabaseEntities : DbContext
    {
        public DnDDatabaseEntities()
            : base("name=DnDDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllowedSpellSave> AllowedSpellSaves { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<CreatureType> CreatureTypes { get; set; }
        public virtual DbSet<Deity> Deities { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<DomainVariant> DomainVariants { get; set; }
        public virtual DbSet<Edition> Editions { get; set; }
        public virtual DbSet<RuleBook> RuleBooks { get; set; }
        public virtual DbSet<AbilityStat> AbilityStats { get; set; }
        public virtual DbSet<Feat> Feats { get; set; }
        public virtual DbSet<FeatCategory> FeatCategories { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<SkillVariant> SkillVariants { get; set; }
        public virtual DbSet<FeatRequiresSaveValue> FeatRequiresSaveValues { get; set; }
        public virtual DbSet<FeatRequiresSkillRank> FeatRequiresSkillRanks { get; set; }
        public virtual DbSet<FeatRequiresStatValue> FeatRequiresStatValues { get; set; }
        public virtual DbSet<FeatVariant> FeatVariants { get; set; }
        public virtual DbSet<Save> Saves { get; set; }
        public virtual DbSet<CreatureSubType> CreatureSubTypes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<MovementMode> MovementModes { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<RaceStatChanx> RaceStatChanges { get; set; }
        public virtual DbSet<RaceVariant> RaceVariants { get; set; }
        public virtual DbSet<RacialMovementMode> RacialMovementModes { get; set; }
        public virtual DbSet<RacialSens> RacialSenses { get; set; }
        public virtual DbSet<SizeCategory> SizeCategories { get; set; }
        public virtual DbSet<SpellDescriptor> SpellDescriptors { get; set; }
        public virtual DbSet<ActionTimeIndicator> ActionTimeIndicators { get; set; }
        public virtual DbSet<Alignment> Alignments { get; set; }
        public virtual DbSet<SaveType> SaveTypes { get; set; }
        public virtual DbSet<SpellSchool> SpellSchools { get; set; }
        public virtual DbSet<SpellSubSchool> SpellSubSchools { get; set; }
        public virtual DbSet<VisualSense> VisualSenses { get; set; }
        public virtual DbSet<DomainSpell> DomainSpells { get; set; }
        public virtual DbSet<Spell> Spells { get; set; }
        public virtual DbSet<SpellVariant> SpellVariants { get; set; }
    }
}
