//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDCharacterSheetTool.Classes.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatRequiresSkillRank
    {
        public int ID { get; set; }
        public int SkillID { get; set; }
        public int FeatID { get; set; }
        public int MinRanks { get; set; }
    
        public virtual Feat Feat { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
