//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterCreator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowedSpellSave
    {
        public int ID { get; set; }
        public int SpellID { get; set; }
        public int SaveStatID { get; set; }
        public int SaveTypeID { get; set; }
        public string Extra { get; set; }
    
        public virtual Save Save { get; set; }
        public virtual SaveType SaveType { get; set; }
    }
}
