//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterCreator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainSpell
    {
        public int SpellID { get; set; }
        public int DomainVariantID { get; set; }
        public int Level { get; set; }
    
        public virtual Spell Spell { get; set; }
        public virtual DomainVariant DomainVariant { get; set; }
    }
}
