//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterCreator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skill()
        {
            this.FeatRequiresSkillRanks = new HashSet<FeatRequiresSkillRank>();
            this.SkillVariants = new HashSet<SkillVariant>();
            this.SkillVariants1 = new HashSet<SkillVariant>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int AbilityStatID { get; set; }
        public bool TrainedOnly { get; set; }
        public int ArmorCheckPenaltyModifier { get; set; }
    
        public virtual AbilityStat AbilityStat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatRequiresSkillRank> FeatRequiresSkillRanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillVariant> SkillVariants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillVariant> SkillVariants1 { get; set; }
    }
}
