//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterCreator.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillVariant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkillVariant()
        {
            this.Skills = new HashSet<Skill>();
        }
    
        public int ID { get; set; }
        public int SkillID { get; set; }
        public int RuleBookID { get; set; }
        public string Description { get; set; }
        public string Action { get; set; }
        public Nullable<bool> TryAgain { get; set; }
        public string Special { get; set; }
        public string Untrained { get; set; }
        public string Restrictions { get; set; }
    
        public virtual RuleBook RuleBook { get; set; }
        public virtual Skill Skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
