//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charisma ähnelt.
        /// </summary>
        public static string AbilityCharisma {
            get {
                return ResourceManager.GetString("AbilityCharisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CHA ähnelt.
        /// </summary>
        public static string AbilityCharismaShort {
            get {
                return ResourceManager.GetString("AbilityCharismaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Constitution ähnelt.
        /// </summary>
        public static string AbilityConstitution {
            get {
                return ResourceManager.GetString("AbilityConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CON ähnelt.
        /// </summary>
        public static string AbilityConstitutionShort {
            get {
                return ResourceManager.GetString("AbilityConstitutionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dexterity ähnelt.
        /// </summary>
        public static string AbilityDexterity {
            get {
                return ResourceManager.GetString("AbilityDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEX ähnelt.
        /// </summary>
        public static string AbilityDexterityShort {
            get {
                return ResourceManager.GetString("AbilityDexterityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intelligence ähnelt.
        /// </summary>
        public static string AbilityIntelligence {
            get {
                return ResourceManager.GetString("AbilityIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INT ähnelt.
        /// </summary>
        public static string AbilityIntelligenceShort {
            get {
                return ResourceManager.GetString("AbilityIntelligenceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strength ähnelt.
        /// </summary>
        public static string AbilityStrength {
            get {
                return ResourceManager.GetString("AbilityStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STR ähnelt.
        /// </summary>
        public static string AbilityStrengthShort {
            get {
                return ResourceManager.GetString("AbilityStrengthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wisdom ähnelt.
        /// </summary>
        public static string AbilityWisdom {
            get {
                return ResourceManager.GetString("AbilityWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WIS ähnelt.
        /// </summary>
        public static string AbilityWisdomShort {
            get {
                return ResourceManager.GetString("AbilityWisdomShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddButton {
            get {
                object obj = ResourceManager.GetObject("AddButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All files ähnelt.
        /// </summary>
        public static string AllFilesFileType {
            get {
                return ResourceManager.GetString("AllFilesFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character saved ähnelt.
        /// </summary>
        public static string ButtonSaveContentNoUnsavedChanges {
            get {
                return ResourceManager.GetString("ButtonSaveContentNoUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save character ähnelt.
        /// </summary>
        public static string ButtonSaveContentUnsavedChanges {
            get {
                return ResourceManager.GetString("ButtonSaveContentUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character sheet ähnelt.
        /// </summary>
        public static string CharacterSheetFileType {
            get {
                return ResourceManager.GetString("CharacterSheetFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to create a new character ähnelt.
        /// </summary>
        public static string ClickToCreateNewCharacter {
            get {
                return ResourceManager.GetString("ClickToCreateNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CloseButton {
            get {
                object obj = ResourceManager.GetObject("CloseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level advancement ähnelt.
        /// </summary>
        public static string ColumnHeaderAbilityScoreAdvancement {
            get {
                return ResourceManager.GetString("ColumnHeaderAbilityScoreAdvancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base value ähnelt.
        /// </summary>
        public static string ColumnHeaderAbilityScoreBaseValue {
            get {
                return ResourceManager.GetString("ColumnHeaderAbilityScoreBaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ability score ähnelt.
        /// </summary>
        public static string ColumnHeaderAbilityScoreName {
            get {
                return ResourceManager.GetString("ColumnHeaderAbilityScoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Character ähnelt.
        /// </summary>
        public static string CreateNewCharacter {
            get {
                return ResourceManager.GetString("CreateNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Character ähnelt.
        /// </summary>
        public static string CreateNewCharacterWindowTitle {
            get {
                return ResourceManager.GetString("CreateNewCharacterWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No character name given ähnelt.
        /// </summary>
        public static string ErrorNoCharacterName {
            get {
                return ResourceManager.GetString("ErrorNoCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No creed alignment given ähnelt.
        /// </summary>
        public static string ErrorNoCreedAlignment {
            get {
                return ResourceManager.GetString("ErrorNoCreedAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No player name is given ähnelt.
        /// </summary>
        public static string ErrorNoPlayerName {
            get {
                return ResourceManager.GetString("ErrorNoPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No profile picture selected ähnelt.
        /// </summary>
        public static string ErrorNoProfilePicture {
            get {
                return ResourceManager.GetString("ErrorNoProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No social alignment given ähnelt.
        /// </summary>
        public static string ErrorNoSocialAlignment {
            get {
                return ResourceManager.GetString("ErrorNoSocialAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExpanderButton {
            get {
                object obj = ResourceManager.GetObject("ExpanderButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ability scores ähnelt.
        /// </summary>
        public static string GroupBoxHeaderAbilityScores {
            get {
                return ResourceManager.GetString("GroupBoxHeaderAbilityScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General infos ähnelt.
        /// </summary>
        public static string GroupBoxHeaderGeneralInfos {
            get {
                return ResourceManager.GetString("GroupBoxHeaderGeneralInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System infos ähnelt.
        /// </summary>
        public static string GroupBoxHeaderMessages {
            get {
                return ResourceManager.GetString("GroupBoxHeaderMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string GroupBoxHeaderNotes {
            get {
                return ResourceManager.GetString("GroupBoxHeaderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile picture ähnelt.
        /// </summary>
        public static string GroupBoxHeaderProfilePicture {
            get {
                return ResourceManager.GetString("GroupBoxHeaderProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alignment ähnelt.
        /// </summary>
        public static string LabelAlignment {
            get {
                return ResourceManager.GetString("LabelAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creed ähnelt.
        /// </summary>
        public static string LabelAlignmentCreed {
            get {
                return ResourceManager.GetString("LabelAlignmentCreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Social ähnelt.
        /// </summary>
        public static string LabelAlignmentSocial {
            get {
                return ResourceManager.GetString("LabelAlignmentSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character name ähnelt.
        /// </summary>
        public static string LabelCharacterName {
            get {
                return ResourceManager.GetString("LabelCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display name ähnelt.
        /// </summary>
        public static string LabelDisplayName {
            get {
                return ResourceManager.GetString("LabelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player name ähnelt.
        /// </summary>
        public static string LabelPlayerName {
            get {
                return ResourceManager.GetString("LabelPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last loaded character ähnelt.
        /// </summary>
        public static string LastLoadedCharacter {
            get {
                return ResourceManager.GetString("LastLoadedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load character has been canceled by the user. ähnelt.
        /// </summary>
        public static string LoadCharacterCancelledMessage {
            get {
                return ResourceManager.GetString("LoadCharacterCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load character... ähnelt.
        /// </summary>
        public static string LoadCharacterDialogTitle {
            get {
                return ResourceManager.GetString("LoadCharacterDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error while loading character. ähnelt.
        /// </summary>
        public static string LoadCharacterExceptionMessage {
            get {
                return ResourceManager.GetString("LoadCharacterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character history ähnelt.
        /// </summary>
        public static string LoadedCharacterHistory {
            get {
                return ResourceManager.GetString("LoadedCharacterHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_Large {
            get {
                object obj = ResourceManager.GetObject("Logo_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_Small {
            get {
                object obj = ResourceManager.GetObject("Logo_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die D&amp;D 3.5 character creator ähnelt.
        /// </summary>
        public static string MainAppTitle {
            get {
                return ResourceManager.GetString("MainAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MaximizeButton {
            get {
                object obj = ResourceManager.GetObject("MaximizeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ability scores ähnelt.
        /// </summary>
        public static string MenuButtonAbilityScores {
            get {
                return ResourceManager.GetString("MenuButtonAbilityScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charactersheet ähnelt.
        /// </summary>
        public static string MenuButtonCharactersheet {
            get {
                return ResourceManager.GetString("MenuButtonCharactersheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Journal ähnelt.
        /// </summary>
        public static string MenuButtonJournal {
            get {
                return ResourceManager.GetString("MenuButtonJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load character ähnelt.
        /// </summary>
        public static string MenuButtonLoadCharacter {
            get {
                return ResourceManager.GetString("MenuButtonLoadCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New character ähnelt.
        /// </summary>
        public static string MenuButtonNewCharacter {
            get {
                return ResourceManager.GetString("MenuButtonNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        public static string MenuButtonProfile {
            get {
                return ResourceManager.GetString("MenuButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ABILITIES ähnelt.
        /// </summary>
        public static string MenuCategoryAbilities {
            get {
                return ResourceManager.GetString("MenuCategoryAbilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CHARACTER ähnelt.
        /// </summary>
        public static string MenuCategoryCharacter {
            get {
                return ResourceManager.GetString("MenuCategoryCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FILES ähnelt.
        /// </summary>
        public static string MenuCategoryFiles {
            get {
                return ResourceManager.GetString("MenuCategoryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLAY ähnelt.
        /// </summary>
        public static string MenuCategoryPlay {
            get {
                return ResourceManager.GetString("MenuCategoryPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MinimizeButton {
            get {
                object obj = ResourceManager.GetObject("MinimizeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NormalizeButton {
            get {
                object obj = ResourceManager.GetObject("NormalizeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No warnings to display. ähnelt.
        /// </summary>
        public static string NoWarningToDisplay {
            get {
                return ResourceManager.GetString("NoWarningToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save character has been canceled by the user. ähnelt.
        /// </summary>
        public static string SaveCharacterCancelledMessage {
            get {
                return ResourceManager.GetString("SaveCharacterCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save character... ähnelt.
        /// </summary>
        public static string SaveCharacterDialogTitle {
            get {
                return ResourceManager.GetString("SaveCharacterDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value less than or equal to zero may mean you are dead or unable to act. ähnelt.
        /// </summary>
        public static string WarningAbilityScoreIsZeroOrBelow {
            get {
                return ResourceManager.GetString("WarningAbilityScoreIsZeroOrBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active character has unsaved changes. Save? ähnelt.
        /// </summary>
        public static string WarningCharacterHasUnsavedChanges {
            get {
                return ResourceManager.GetString("WarningCharacterHasUnsavedChanges", resourceCulture);
            }
        }
    }
}
