//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All files ähnelt.
        /// </summary>
        public static string AllFilesFileType {
            get {
                return ResourceManager.GetString("AllFilesFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character sheet ähnelt.
        /// </summary>
        public static string CharacterSheetFileType {
            get {
                return ResourceManager.GetString("CharacterSheetFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last loaded character ähnelt.
        /// </summary>
        public static string LastLoadedCharacter {
            get {
                return ResourceManager.GetString("LastLoadedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load character has been canceled by the user. ähnelt.
        /// </summary>
        public static string LoadCharacterCancelledMessage {
            get {
                return ResourceManager.GetString("LoadCharacterCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load character... ähnelt.
        /// </summary>
        public static string LoadCharacterDialogTitle {
            get {
                return ResourceManager.GetString("LoadCharacterDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error while loading character. ähnelt.
        /// </summary>
        public static string LoadCharacterExceptionMessage {
            get {
                return ResourceManager.GetString("LoadCharacterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character history ähnelt.
        /// </summary>
        public static string LoadedCharacterHistory {
            get {
                return ResourceManager.GetString("LoadedCharacterHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die D&amp;D 3.5 character creator ähnelt.
        /// </summary>
        public static string MainAppTitle {
            get {
                return ResourceManager.GetString("MainAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charactersheet ähnelt.
        /// </summary>
        public static string MenuButtonCharactersheet {
            get {
                return ResourceManager.GetString("MenuButtonCharactersheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Journal ähnelt.
        /// </summary>
        public static string MenuButtonJournal {
            get {
                return ResourceManager.GetString("MenuButtonJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load character ähnelt.
        /// </summary>
        public static string MenuButtonLoadCharacter {
            get {
                return ResourceManager.GetString("MenuButtonLoadCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New character ähnelt.
        /// </summary>
        public static string MenuButtonNewCharacter {
            get {
                return ResourceManager.GetString("MenuButtonNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        public static string MenuButtonProfile {
            get {
                return ResourceManager.GetString("MenuButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CHARACTER ähnelt.
        /// </summary>
        public static string MenuCategoryCharacter {
            get {
                return ResourceManager.GetString("MenuCategoryCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FILES ähnelt.
        /// </summary>
        public static string MenuCategoryFiles {
            get {
                return ResourceManager.GetString("MenuCategoryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLAY ähnelt.
        /// </summary>
        public static string MenuCategoryPlay {
            get {
                return ResourceManager.GetString("MenuCategoryPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save character has been canceled by the user. ähnelt.
        /// </summary>
        public static string SaveCharacterCancelledMessage {
            get {
                return ResourceManager.GetString("SaveCharacterCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save character... ähnelt.
        /// </summary>
        public static string SaveCharacterDialogTitle {
            get {
                return ResourceManager.GetString("SaveCharacterDialogTitle", resourceCulture);
            }
        }
    }
}
